version: "3"

volumes:
  mongodb_volume:

services:
  bilim:
    build: ./
    restart: always
    volumes:
      - ${LocationProfileImage}:${LocationProfileImage}
    ports:
      - 4000:${APIPortHTTP}
      - 8080:${StaticPortHTTP}
    environment:
      - MONGO_HOST=mongodb://mongodb:27017

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
    restart: always